### ISSUE TITLE
list-all fails on MacOS due to `tac` missing by default

### ISSUE THREAD

**Issue by whaley** [skotchpine/asdf-maven#10]
`tac` is not installed by default on MacOS.  `asdf list-all maven` fails as a result.  I would suggest removing the call to tac, and list all maven versions in descending order, or detecting if `tac` is available and only piping to it if so. 

... and/or provide a gentle suggestion to install coreutils (`brew install coreutils`) and symlink gtac to tac

**Comment by burnettk** [comment]
this also bit me. `tail -r the-file` apparently works, according to https://unix.stackexchange.com/questions/114041/how-can-i-get-the-tac-command-on-os-x.

**Comment by skotchpine** [comment]
Can someone confirm that this works and close? I'm without osx atm

**Comment by whaley** [comment]
@whitfin ^

**Comment by whitfin** [comment]
@whaley we meet again!

It seems fine, but we can probably remove the conditional and just `| sort` I think (or `| sort -r` for the opposite direction). This should be portable and avoid the condition on platform.

**Comment by whitfin** [comment]
(cross referencing a patch to use `sort`: https://github.com/skotchpine/asdf-maven/pull/13)

**Comment by whaley** [comment]
I've confirmed just piping to `sort` works on MacOS (10.13.6) and on Linux (Ubuntu 18.04).  It's probably reasonable to expect `sort` to be available everywhere.
