### ISSUE TITLE
JAVA_HOME not found

### ISSUE THREAD

**Issue by HereThereBeMonsters** [skotchpine/asdf-maven#22]
Related to #3 and/or #20.

I installed Java (open JDK 11) and Maven 3.6.0 using asdf on Ubuntu 18.10. I am using bash for this.

I added a call to the java wrapper in my `.bashrc.`:
```
. $HOME/.asdf/plugins/java/asdf-java-wrapper.bash
```
When I open a shell, and execute `echo $JAVA_HOME` the output is correct and shows the asdf install dir of the JDK. 

```
~$ echo $JAVA_HOME
/home/henry/.asdf/installs/java/openjdk-11.0.1
```

But when I run Maven it somehow loses the value of JAVA_HOME and shows:

```
~$ mvn
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

**Comment by drjonnicholson** [comment]
Sounds like the same, try doing `echo "\"$(asdf current java | sed -s 's|\(.*\) \?(.*|\1|g')\""` and see if it's got that trailing space

**Comment by execb5** [comment]
> 
> 
> Sounds like the same, try doing `echo "\"$(asdf current java | sed -s 's|\(.*\) \?(.*|\1|g')\""` and see if it's got that trailing space

I also have that trailing space when executing that command. Is there any work arounds to make it work?

**Comment by drjonnicholson** [comment]
Yes, but no idea when they'll be merged. So far there's two PRs that do the same thing... https://github.com/skotchpine/asdf-maven/pull/21, and https://github.com/skotchpine/asdf-maven/pull/25

**Comment by williamokano** [comment]
I changed my local exec-env as the PR #24 did and it worked good here. Any updated when it will be fixed?

**Comment by Hacklor** [comment]
> Sounds like the same, try doing `echo "\"$(asdf current java | sed -s 's|\(.*\) \?(.*|\1|g')\""` and see if it's got that trailing space

I'm experiencing the same problem, and it's great to see that a solution is ready to be merged. But that doesn't help me (and many others?) yet.

@skotchpine When will it be fixed / merged?
