### ISSUE TITLE
Dynamically populate the Maven versions

### ISSUE THREAD

**Issue by whitfin** [skotchpine/asdf-maven#5]
Right now there's a bunch of arbitrary versions just echoed out. Is it possible to seed a list from elsewhere?

**Comment by skotchpine** [comment]
I'll look into this today.

**Comment by whitfin** [comment]
@skotchpine it seems that you could maybe scrape https://maven.apache.org/docs/history.html - I could take a look at this if you want. It'd probably be gross due to bash... but hey :)

**Comment by whitfin** [comment]
Hey @skotchpine - filed something basic over here: https://github.com/skotchpine/asdf-maven/pull/6. We can probably improve it in future though (but I propose that it's better than hardcoding a few versions).

**Comment by skotchpine** [comment]
Thanks for the commit :)
